/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package halaman_admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ACER
 */
public class DataBuku extends javax.swing.JInternalFrame {

    Connection conn = Koneksi.kon.conn();
    Statement s;
    ResultSet r;
    ResultSet rs;
    String sql1;
    DefaultTableModel model;
    
    
    
    public DataBuku() {
        initComponents();
        judul();
        tampildata();
        kode_buku.setEditable(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        autokodebuku();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public Boolean tidak_kosong(){
        return !(kode_buku.getText().equals("") || judul.getText().equals("") || penerbit.getText().equals("") || tahun.getText().equals("") || ckategori.getSelectedItem().equals("") || jumlah.getText().equals(""));
    }
     
     public void reset(){
        judul.setText(null);
        penerbit.setText(null);
        tahun.setText(null);
        ckategori.setSelectedIndex(0);
        jumlah.setText(null);
    }
     
      
       public void autokodebuku(){
         try{
            String sql;
            sql = "SELECT COUNT(id_buku) as jumlah FROM buku";
            s = conn.createStatement();
            rs = s.executeQuery(sql);
            if (rs.next()) {
                String jumlah = rs.getString("jumlah");
                int jumint = Integer.parseInt(String.valueOf(jumlah));
                if (jumint > 0) {
                    s = conn.createStatement();
                        sql = "SELECT MAX(id_buku) AS kode FROM buku";
                        rs = s.executeQuery(sql);
                        if(rs.next()){
                            String id = rs.getString("kode").substring(2);
                            String kode = String.valueOf(Integer.parseInt(id) + 1);
                            if(kode.length() == 1){
                               kode_buku.setText("BK00"+kode);
                            }else if(kode.length() == 2){
                                kode_buku.setText("BK00"+kode);
                            }else
                                kode_buku.setText("BK"+kode);
                        }
                }else{
                    kode_buku.setText("BK001");
                }
            }
        }catch(SQLException e){
            
        }
    }
    
     public void judul(){
        Object[] judul = {"ID","Judul","Penerbit","Tahun Terbit","Kategor","Jumlah"};
        model = new DefaultTableModel(null,judul){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tblbuku.setModel(model);
    }
     
     public void judul_cari(){
        Object[] judul = {"ID","Judul","Penerbit","Tahun Terbit","Kategor","Jumlah"};
        model = new DefaultTableModel(null,judul){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tblbuku.setModel(model);
    }
     
     public void tampildata(){
        try{
            s = conn.createStatement();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            rs = s.executeQuery("SELECT * FROM buku ORDER BY id_buku DESC");
            while(rs.next()){
                Object [] data = {
                    rs.getString("id_buku"),
                    rs.getString("judul"),
                    rs.getString("penerbit"),
                    rs.getString("tahun_terbit"),
                    rs.getString("kategori"),
                    rs.getString("jumlah"),
                };
                model.addRow(data);
                model.getRowCount();
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        kode_buku = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        penerbit = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        ckategori = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbuku1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        kode_buku1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        judul1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        penerbit1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        tahun1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        kategori1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jumlah1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        reset1 = new javax.swing.JButton();
        tambah1 = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        ubah1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1320, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1320, 710));

        tblbuku.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        tblbuku.setForeground(new java.awt.Color(0, 51, 153));
        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblbuku.setGridColor(new java.awt.Color(28, 42, 57));
        tblbuku.setSelectionBackground(new java.awt.Color(28, 42, 57));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbuku);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("Kode Buku");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        kode_buku.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        kode_buku.setForeground(new java.awt.Color(0, 51, 153));
        kode_buku.setBorder(null);
        jPanel7.add(kode_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 370, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 51, 153));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 390, 10));

        jLabel14.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Judul Buku");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        judul.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 51, 153));
        judul.setBorder(null);
        jPanel7.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 370, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 51, 153));
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 390, 10));

        jLabel15.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("Penerbit");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        penerbit.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        penerbit.setForeground(new java.awt.Color(0, 51, 153));
        penerbit.setBorder(null);
        penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitActionPerformed(evt);
            }
        });
        jPanel7.add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 164, 370, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 51, 153));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 390, 10));

        jLabel16.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText("Tahun Terbit");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        tahun.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        tahun.setForeground(new java.awt.Color(0, 51, 153));
        tahun.setBorder(null);
        tahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tahunKeyTyped(evt);
            }
        });
        jPanel7.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 228, 370, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 51, 153));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 390, 10));

        jLabel17.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("Kategori");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 267, -1, -1));

        jLabel18.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("Jumlah");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 331, -1, -1));

        jumlah.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jumlah.setForeground(new java.awt.Color(28, 42, 57));
        jumlah.setBorder(null);
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        jPanel7.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 356, 370, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 51, 153));
        jPanel7.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 379, 390, 10));

        reset.setBackground(new java.awt.Color(0, 51, 153));
        reset.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/reload.png"))); // NOI18N
        reset.setText("Reset");
        reset.setBorder(null);
        reset.setContentAreaFilled(false);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.setOpaque(true);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel7.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 92, 37));

        tambah.setBackground(new java.awt.Color(0, 51, 153));
        tambah.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/add-square-button.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.setBorder(null);
        tambah.setContentAreaFilled(false);
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.setOpaque(true);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel7.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 92, 37));

        hapus.setBackground(new java.awt.Color(0, 51, 153));
        hapus.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/garbage.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.setOpaque(true);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel7.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 92, 37));

        ubah.setBackground(new java.awt.Color(0, 51, 153));
        ubah.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/edit.png"))); // NOI18N
        ubah.setText("Ubah");
        ubah.setBorder(null);
        ubah.setContentAreaFilled(false);
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.setOpaque(true);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel7.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 92, 37));

        ckategori.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        ckategori.setForeground(new java.awt.Color(0, 51, 153));
        ckategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Silahkan Pilih-", "komik", "novel", "pendidikan", "fiksi" }));
        jPanel7.add(ckategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 380, -1));

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Data Buku");

        tcari.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        tcari.setForeground(new java.awt.Color(0, 51, 153));
        tcari.setBorder(null);
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
        });

        jSeparator18.setForeground(new java.awt.Color(0, 51, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/magnifying-glass (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(830, 670));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1338, 669));

        tblbuku1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tblbuku1.setForeground(new java.awt.Color(28, 42, 57));
        tblbuku1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbuku1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblbuku1.setGridColor(new java.awt.Color(28, 42, 57));
        tblbuku1.setSelectionBackground(new java.awt.Color(28, 42, 57));
        tblbuku1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbuku1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblbuku1);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(28, 42, 57));
        jLabel19.setText("Kode Buku");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        kode_buku1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        kode_buku1.setForeground(new java.awt.Color(28, 42, 57));
        kode_buku1.setBorder(null);
        jPanel8.add(kode_buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 370, -1));

        jSeparator12.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 390, 10));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(28, 42, 57));
        jLabel20.setText("Judul Buku");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        judul1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        judul1.setForeground(new java.awt.Color(28, 42, 57));
        judul1.setBorder(null);
        jPanel8.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 370, -1));

        jSeparator13.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 390, 10));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(28, 42, 57));
        jLabel21.setText("Penerbit");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        penerbit1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        penerbit1.setForeground(new java.awt.Color(28, 42, 57));
        penerbit1.setBorder(null);
        penerbit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbit1ActionPerformed(evt);
            }
        });
        jPanel8.add(penerbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 164, 370, -1));

        jSeparator14.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 390, 10));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(28, 42, 57));
        jLabel22.setText("Tahun Terbit");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        tahun1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tahun1.setForeground(new java.awt.Color(28, 42, 57));
        tahun1.setBorder(null);
        tahun1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tahun1KeyTyped(evt);
            }
        });
        jPanel8.add(tahun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 228, 370, -1));

        jSeparator15.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 390, 10));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(28, 42, 57));
        jLabel23.setText("Kategori");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 267, -1, -1));

        kategori1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        kategori1.setForeground(new java.awt.Color(28, 42, 57));
        kategori1.setBorder(null);
        jPanel8.add(kategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 292, 370, -1));

        jSeparator16.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 315, 390, 10));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(28, 42, 57));
        jLabel24.setText("Jumlah");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 331, -1, -1));

        jumlah1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jumlah1.setForeground(new java.awt.Color(28, 42, 57));
        jumlah1.setBorder(null);
        jumlah1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlah1KeyTyped(evt);
            }
        });
        jPanel8.add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 356, 370, -1));

        jSeparator17.setForeground(new java.awt.Color(28, 42, 57));
        jPanel8.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 379, 390, 10));

        reset1.setBackground(new java.awt.Color(28, 42, 57));
        reset1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        reset1.setForeground(new java.awt.Color(255, 255, 255));
        reset1.setText("Reset");
        reset1.setBorder(null);
        reset1.setContentAreaFilled(false);
        reset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset1.setOpaque(true);
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        jPanel8.add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 92, 37));

        tambah1.setBackground(new java.awt.Color(28, 42, 57));
        tambah1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tambah1.setForeground(new java.awt.Color(255, 255, 255));
        tambah1.setText("Tambah");
        tambah1.setBorder(null);
        tambah1.setContentAreaFilled(false);
        tambah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah1.setOpaque(true);
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });
        jPanel8.add(tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 92, 37));

        hapus1.setBackground(new java.awt.Color(28, 42, 57));
        hapus1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        hapus1.setForeground(new java.awt.Color(255, 255, 255));
        hapus1.setText("Hapus");
        hapus1.setBorder(null);
        hapus1.setContentAreaFilled(false);
        hapus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus1.setOpaque(true);
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });
        jPanel8.add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 92, 37));

        ubah1.setBackground(new java.awt.Color(28, 42, 57));
        ubah1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ubah1.setForeground(new java.awt.Color(255, 255, 255));
        ubah1.setText("Ubah");
        ubah1.setBorder(null);
        ubah1.setContentAreaFilled(false);
        ubah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah1.setOpaque(true);
        ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah1ActionPerformed(evt);
            }
        });
        jPanel8.add(ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 92, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jInternalFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:
        int baris = tblbuku.getSelectedRow();
        ubah.setEnabled(true);
        hapus.setEnabled(true);
        kode_buku.setText(tblbuku.getModel().getValueAt(baris, 0).toString());
        judul.setText(tblbuku.getModel().getValueAt(baris, 1).toString());
        penerbit.setText(tblbuku.getModel().getValueAt(baris, 2).toString());
        tahun.setText(tblbuku.getModel().getValueAt(baris, 3).toString());
        ckategori.setSelectedItem(tblbuku.getModel().getValueAt(baris, 4).toString());
        jumlah.setText(tblbuku.getModel().getValueAt(baris, 5).toString());

    }//GEN-LAST:event_tblbukuMouseClicked

    private void penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerbitActionPerformed

    private void tahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) || tahun.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_tahunKeyTyped

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()) || jumlah.getText().length()>=7){
            evt.consume();
        }
    }//GEN-LAST:event_jumlahKeyTyped

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
        autokodebuku();
    }//GEN-LAST:event_resetActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        if(tidak_kosong()){
            try {
                s = conn.createStatement();
                String sql = "INSERT INTO buku VALUES('"+ kode_buku.getText() +"','"+ judul.getText() +"','"+ penerbit.getText() +"','"+ tahun.getText() +"', '"+ ckategori.getSelectedItem() +"','"+ jumlah.getText() +"')";
                s.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Buku Berhasil DiTambahkan");
                reset();
                tampildata();
                autokodebuku();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                reset();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if(!kode_buku.getText().equals("")){
            try {
                int jawab;
                if((jawab = JOptionPane.showConfirmDialog(null,"Hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                    s = conn.createStatement();
                    String sql = "DELETE FROM buku WHERE id_buku='"+ kode_buku.getText() +"'";
                    s.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Data Buku Berhasil di hapus");
                    reset();
                    tampildata();
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                reset();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Pilih ID untuk data yang ingin di hapus!");
        }

    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        if(tidak_kosong()){
            try {
                s = conn.createStatement();
                String sql = "UPDATE buku SET judul='"+ judul.getText() +"', penerbit='"+ penerbit.getText() +"',tahun_terbit='"+ tahun.getText() +"',kategori='"+ ckategori.getSelectedItem() +"',jumlah='"+ jumlah.getText() +"' WHERE id_buku='"+ kode_buku.getText() +"'";
                s.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Buku Berhasil di ubah");
                reset();
                tampildata();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                reset();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ubahActionPerformed

    private void tblbuku1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbuku1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbuku1MouseClicked

    private void penerbit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerbit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerbit1ActionPerformed

    private void tahun1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahun1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun1KeyTyped

    private void jumlah1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1KeyTyped

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1ActionPerformed

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah1ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus1ActionPerformed

    private void ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubah1ActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        // TODO add your handling code here:
       try {
            s = conn.createStatement();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            String cr = tcari.getText();
            rs = s.executeQuery("SELECT * FROM buku WHERE id_buku like '%"+ cr +"%'or judul like '%"+ cr +"%'or penerbit like '%"+ cr +"%' or tahun_terbit like '%"+ cr +"%' or kategori like '%"+ cr +"%' or jumlah like '%"+ cr +"%' ORDER BY id_buku DESC " );
             while (rs.next()){
                    Object[] data ={
                     rs.getString("id_buku"),
                     rs.getString("judul"),
                     rs.getString("penerbit"),
                     rs.getString("tahun_terbit"),
                     rs.getString("kategori"),
                     rs.getString("jumlah"),
                    };
                    model.addRow(data);
                    }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_tcariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ckategori;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField judul1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JTextField kategori1;
    private javax.swing.JTextField kode_buku;
    private javax.swing.JTextField kode_buku1;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField penerbit1;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JTextField tahun;
    private javax.swing.JTextField tahun1;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tambah1;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTable tblbuku1;
    private javax.swing.JTextField tcari;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubah1;
    // End of variables declaration//GEN-END:variables
}
