/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package halaman_admin;

import aplikasi_perpustakaan.FrmLogin;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MenuUtamaAdmin extends javax.swing.JFrame {

    Color panedefault;
    Color paneClick;
    public MenuUtamaAdmin() {
        initComponents();
        
        panedefault = new Color(0, 0, 153);
        paneClick = new Color(0, 51, 102);
        
        panesiswa.setBackground(paneClick);
        panebuku.setBackground(panedefault);
        panepeminjaman.setBackground(panedefault);
        panepengembalian.setBackground(panedefault);
        
        DataSiswa ds = new DataSiswa();
        mainpanel.add(ds).setVisible(true);
    }
    
     public void close(){
        int selectedOption = JOptionPane.showConfirmDialog(null,"Konfirmasi Tutup Sistem", "Tutup Sistem", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimsize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sidebarpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bpeminjaman = new javax.swing.JPanel();
        panepeminjaman = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Bpengembalian = new javax.swing.JPanel();
        panepengembalian = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BLogout = new javax.swing.JButton();
        Bbuku = new javax.swing.JPanel();
        panebuku = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Bsiswa = new javax.swing.JPanel();
        panesiswa = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerpanel.setBackground(new java.awt.Color(0, 51, 102));
        headerpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerpanelMouseDragged(evt);
            }
        });
        headerpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerpanelMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        minimsize.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        minimsize.setForeground(new java.awt.Color(255, 255, 255));
        minimsize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimsize.setText("-");
        minimsize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimsizeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perpustakaan");

        javax.swing.GroupLayout headerpanelLayout = new javax.swing.GroupLayout(headerpanel);
        headerpanel.setLayout(headerpanelLayout);
        headerpanelLayout.setHorizontalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerpanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1362, Short.MAX_VALUE)
                .addComponent(minimsize, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        headerpanelLayout.setVerticalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addGroup(headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimsize)
                    .addComponent(exit))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        getContentPane().add(headerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1640, 40));

        sidebarpanel.setBackground(new java.awt.Color(0, 51, 153));

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/perpus.png"))); // NOI18N

        Bpeminjaman.setBackground(new java.awt.Color(0, 51, 153));
        Bpeminjaman.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Bpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpeminjamanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BpeminjamanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panepeminjamanLayout = new javax.swing.GroupLayout(panepeminjaman);
        panepeminjaman.setLayout(panepeminjamanLayout);
        panepeminjamanLayout.setHorizontalGroup(
            panepeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panepeminjamanLayout.setVerticalGroup(
            panepeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Data Peminjaman");

        javax.swing.GroupLayout BpeminjamanLayout = new javax.swing.GroupLayout(Bpeminjaman);
        Bpeminjaman.setLayout(BpeminjamanLayout);
        BpeminjamanLayout.setHorizontalGroup(
            BpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpeminjamanLayout.createSequentialGroup()
                .addComponent(panepeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BpeminjamanLayout.setVerticalGroup(
            BpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panepeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bpengembalian.setBackground(new java.awt.Color(0, 51, 153));
        Bpengembalian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Bpengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BpengembalianMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BpengembalianMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panepengembalianLayout = new javax.swing.GroupLayout(panepengembalian);
        panepengembalian.setLayout(panepengembalianLayout);
        panepengembalianLayout.setHorizontalGroup(
            panepengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panepengembalianLayout.setVerticalGroup(
            panepengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Data Pengembalian");

        javax.swing.GroupLayout BpengembalianLayout = new javax.swing.GroupLayout(Bpengembalian);
        Bpengembalian.setLayout(BpengembalianLayout);
        BpengembalianLayout.setHorizontalGroup(
            BpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpengembalianLayout.createSequentialGroup()
                .addComponent(panepengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        BpengembalianLayout.setVerticalGroup(
            BpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BpengembalianLayout.createSequentialGroup()
                .addGroup(BpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BpengembalianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addComponent(panepengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        BLogout.setBackground(new java.awt.Color(0, 51, 153));
        BLogout.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        BLogout.setForeground(new java.awt.Color(255, 255, 255));
        BLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/logout.png"))); // NOI18N
        BLogout.setText("Sign Out");
        BLogout.setBorder(null);
        BLogout.setContentAreaFilled(false);
        BLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLogout.setOpaque(true);
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        Bbuku.setBackground(new java.awt.Color(0, 51, 153));
        Bbuku.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Bbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BbukuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BbukuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panebukuLayout = new javax.swing.GroupLayout(panebuku);
        panebuku.setLayout(panebukuLayout);
        panebukuLayout.setHorizontalGroup(
            panebukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panebukuLayout.setVerticalGroup(
            panebukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data Buku");

        javax.swing.GroupLayout BbukuLayout = new javax.swing.GroupLayout(Bbuku);
        Bbuku.setLayout(BbukuLayout);
        BbukuLayout.setHorizontalGroup(
            BbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BbukuLayout.createSequentialGroup()
                .addComponent(panebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BbukuLayout.setVerticalGroup(
            BbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BbukuLayout.createSequentialGroup()
                .addGroup(BbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BbukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(panebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        Bsiswa.setBackground(new java.awt.Color(0, 51, 153));
        Bsiswa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Bsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BsiswaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BsiswaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panesiswaLayout = new javax.swing.GroupLayout(panesiswa);
        panesiswa.setLayout(panesiswaLayout);
        panesiswaLayout.setHorizontalGroup(
            panesiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panesiswaLayout.setVerticalGroup(
            panesiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Siswa");

        javax.swing.GroupLayout BsiswaLayout = new javax.swing.GroupLayout(Bsiswa);
        Bsiswa.setLayout(BsiswaLayout);
        BsiswaLayout.setHorizontalGroup(
            BsiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BsiswaLayout.createSequentialGroup()
                .addComponent(panesiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BsiswaLayout.setVerticalGroup(
            BsiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BsiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panesiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin");

        jLabel7.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SDN Kadu 1");

        javax.swing.GroupLayout sidebarpanelLayout = new javax.swing.GroupLayout(sidebarpanel);
        sidebarpanel.setLayout(sidebarpanelLayout);
        sidebarpanelLayout.setHorizontalGroup(
            sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bpeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bpengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bsiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarpanelLayout.createSequentialGroup()
                .addGroup(sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarpanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarpanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7)))
                    .addGroup(sidebarpanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarpanelLayout.setVerticalGroup(
            sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarpanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(sidebarpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Bsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        getContentPane().add(sidebarpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 710));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setPreferredSize(new java.awt.Dimension(1320, 710));

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_exitMouseClicked

    int x,y;
    
    private void minimsizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimsizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_minimsizeMouseClicked

    private void headerpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerpanelMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_headerpanelMouseDragged

    private void headerpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerpanelMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_headerpanelMousePressed

    private void BpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpeminjamanMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        DataPeminjaman dpem = new DataPeminjaman();
        mainpanel.add(dpem).setVisible(true);
    }//GEN-LAST:event_BpeminjamanMouseClicked

    private void BpeminjamanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpeminjamanMousePressed
        // TODO add your handling code here:
        panepeminjaman.setBackground(paneClick);
        panesiswa.setBackground(panedefault);
        panebuku.setBackground(panedefault);
        panepengembalian.setBackground(panedefault);
    }//GEN-LAST:event_BpeminjamanMousePressed

    private void BpengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpengembalianMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        DataPengembalian dpen = new DataPengembalian();
        mainpanel.add(dpen).setVisible(true);
    }//GEN-LAST:event_BpengembalianMouseClicked

    private void BpengembalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpengembalianMousePressed
        // TODO add your handling code here:
    panepengembalian.setBackground(paneClick);
        panesiswa.setBackground(panedefault);
        panebuku.setBackground(panedefault);
        panepeminjaman.setBackground(panedefault);
    }//GEN-LAST:event_BpengembalianMousePressed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        // TODO add your handling code here:
        FrmLogin logut = new FrmLogin();
        logut.setVisible(true);
        dispose();
    }//GEN-LAST:event_BLogoutActionPerformed

    private void BbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbukuMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        DataBuku db = new DataBuku();
        mainpanel.add(db).setVisible(true);
    }//GEN-LAST:event_BbukuMouseClicked

    private void BbukuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbukuMousePressed
        // TODO add your handling code here:
        panebuku.setBackground(paneClick);
        panesiswa.setBackground(panedefault);
        panepeminjaman.setBackground(panedefault);
        panepengembalian.setBackground(panedefault);
    }//GEN-LAST:event_BbukuMousePressed

    private void BsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsiswaMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        DataSiswa ds = new DataSiswa();
        mainpanel.add(ds).setVisible(true);
    }//GEN-LAST:event_BsiswaMouseClicked

    private void BsiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsiswaMousePressed
        // TODO add your handling code here:
        panesiswa.setBackground(paneClick);
        panebuku.setBackground(panedefault);
        panepeminjaman.setBackground(panedefault);
        panepengembalian.setBackground(panedefault);
    }//GEN-LAST:event_BsiswaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogout;
    private javax.swing.JPanel Bbuku;
    private javax.swing.JPanel Bpeminjaman;
    private javax.swing.JPanel Bpengembalian;
    private javax.swing.JPanel Bsiswa;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JDesktopPane mainpanel;
    private javax.swing.JLabel minimsize;
    private javax.swing.JPanel panebuku;
    private javax.swing.JPanel panepeminjaman;
    private javax.swing.JPanel panepengembalian;
    private javax.swing.JPanel panesiswa;
    private javax.swing.JPanel sidebarpanel;
    // End of variables declaration//GEN-END:variables
}
