/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplikasi_perpustakaan;

import Koneksi.kon;
import com.sun.glass.events.KeyEvent;
import halaman_admin.MenuUtamaAdmin;
import halaman_siswa.FrmDaftar;
import halaman_siswa.MenuUtamaSiswa;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class FrmLogin extends javax.swing.JFrame {

     MenuUtamaAdmin menu1 = new MenuUtamaAdmin();
    MenuUtamaSiswa menu2 = new MenuUtamaSiswa();
    
    private void Login(){
        try {
           Connection conn = kon.conn();
           Statement s = conn.createStatement();
           String sql = "SELECT * FROM user_login where username='"+Tuser.getText() +"'and password='"+ Tpass.getText()+"'";
           ResultSet rs = s.executeQuery(sql);
           
            if (rs.next()) {
               String akses = rs.getString("akses");
               switch (akses) {
                   case "admin":
                       menu1.setVisible(true);
                       this.dispose();
                       break;
                   case "siswa":
                       menu2.setVisible(true);
                       this.dispose();
                       break;
               }
            }else{
                JOptionPane.showMessageDialog(null, "Gagal Login bro");                
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            
        }
    }
    
    private void bersih(){
        Tuser.setText("");
        Tpass.setText("");
        Tuser.requestFocus();
    }
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bodypane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Bdaftar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Bmasuk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tpass = new javax.swing.JPasswordField();
        exit = new javax.swing.JLabel();
        minimsize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bodypane.setBackground(new java.awt.Color(255, 255, 255));
        Bodypane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BodypaneMouseDragged(evt);
            }
        });
        Bodypane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BodypaneMousePressed(evt);
            }
        });
        Bodypane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Or");
        Bodypane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        Tuser.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        Tuser.setForeground(new java.awt.Color(0, 51, 153));
        Tuser.setBorder(null);
        Tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TuserKeyPressed(evt);
            }
        });
        Bodypane.add(Tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        Bodypane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 10));

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Password");
        Bodypane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 153));
        Bodypane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 320, 10));

        Bdaftar.setBackground(new java.awt.Color(26, 177, 136));
        Bdaftar.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        Bdaftar.setForeground(new java.awt.Color(255, 255, 255));
        Bdaftar.setText("Sign Up");
        Bdaftar.setBorder(null);
        Bdaftar.setContentAreaFilled(false);
        Bdaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bdaftar.setOpaque(true);
        Bdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdaftarActionPerformed(evt);
            }
        });
        Bodypane.add(Bdaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 320, 40));

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Silakan Masuk");
        Bodypane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, -1));

        Bmasuk.setBackground(new java.awt.Color(0, 51, 153));
        Bmasuk.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        Bmasuk.setForeground(new java.awt.Color(255, 255, 255));
        Bmasuk.setText("Sign In");
        Bmasuk.setBorder(null);
        Bmasuk.setContentAreaFilled(false);
        Bmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bmasuk.setOpaque(true);
        Bmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmasukActionPerformed(evt);
            }
        });
        Bodypane.add(Bmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 320, 40));

        jLabel7.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Username");
        Bodypane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, -1));

        Tpass.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        Tpass.setForeground(new java.awt.Color(0, 51, 153));
        Tpass.setBorder(null);
        Tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TpassKeyPressed(evt);
            }
        });
        Bodypane.add(Tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 320, -1));

        exit.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 51, 153));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        Bodypane.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, -1));

        minimsize.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        minimsize.setForeground(new java.awt.Color(0, 51, 153));
        minimsize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimsize.setText("-");
        minimsize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimsizeMouseClicked(evt);
            }
        });
        Bodypane.add(minimsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 20, -1));

        getContentPane().add(Bodypane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 410, 500));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/perpus.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SDN KADU 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Perpustakaan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/background-4876988_960_720.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdaftarActionPerformed
        // TODO add your handling code here:
       FrmDaftar daftar = new FrmDaftar();
       daftar.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BdaftarActionPerformed

    private void BmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmasukActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_BmasukActionPerformed

    private void TuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TuserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Login();
            bersih();
        }
    }//GEN-LAST:event_TuserKeyPressed

    private void TpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Login();
            bersih();
        }
    }//GEN-LAST:event_TpassKeyPressed

    int x,y;
    
    private void BodypaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BodypaneMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_BodypaneMouseDragged

    private void BodypaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BodypaneMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BodypaneMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minimsizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimsizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_minimsizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdaftar;
    private javax.swing.JButton Bmasuk;
    private javax.swing.JPanel Bodypane;
    private javax.swing.JPasswordField Tpass;
    private javax.swing.JTextField Tuser;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimsize;
    // End of variables declaration//GEN-END:variables
}
