/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package halaman_siswa;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ACER
 */
public class DataPengembalian extends javax.swing.JInternalFrame {

    Statement s;
    ResultSet rs;
    Connection conn = Koneksi.kon.conn();
    DefaultTableModel model;
    public DataPengembalian() {
        initComponents();
        judul_pengembalian();
        tampildata_pengembalian();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public void judul_pengembalian(){
        Object[] judul = {"No kembali","No pinjam","NIS","Id Buku","Tanggal kembali", "denda", "keterangan","jumlah"};
        model = new DefaultTableModel(null,judul){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tkembali.setModel(model);
    }
    
    public void tampildata_pengembalian(){
        try{
            s = conn.createStatement();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            rs = s.executeQuery("SELECT * FROM pengembalian ORDER BY tgl_kembali DESC");
            while(rs.next()){
                Object [] data = {
                    rs.getString("no_kembali"),
                    rs.getString("no_pinjam"),
                    rs.getString("NIS"),
                    rs.getString("id_buku"),
                    rs.getString("tgl_kembali"),
                    rs.getString("denda"),
                    rs.getString("keterangan"),
                    rs.getString("jumlah"),
                };
                model.addRow(data);
                model.getRowCount();
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tkembali = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        masuk_admin1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(990, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Data Pengembalian Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 13, -1, -1));

        tkembali.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        tkembali.setForeground(new java.awt.Color(0, 51, 153));
        tkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tkembali);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 113, 946, -1));

        tcari.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        tcari.setForeground(new java.awt.Color(0, 51, 153));
        tcari.setBorder(null);
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
        });
        jPanel1.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 320, 10));

        masuk_admin1.setBackground(new java.awt.Color(0, 51, 153));
        masuk_admin1.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        masuk_admin1.setForeground(new java.awt.Color(255, 255, 255));
        masuk_admin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/reload.png"))); // NOI18N
        masuk_admin1.setText("Resfresh Table");
        masuk_admin1.setBorder(null);
        masuk_admin1.setContentAreaFilled(false);
        masuk_admin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_admin1.setOpaque(true);
        masuk_admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_admin1ActionPerformed(evt);
            }
        });
        jPanel1.add(masuk_admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 562, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon pack/magnifying-glass (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masuk_admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_admin1ActionPerformed
        // TODO add your handling code here:
        tampildata_pengembalian();
    }//GEN-LAST:event_masuk_admin1ActionPerformed

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        // TODO add your handling code here:
         try {
            s = conn.createStatement();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            String cr = tcari.getText();
            rs = s.executeQuery("SELECT * FROM pengembalian WHERE no_kembali like '%"+ cr +"%' or no_pinjam like '%"+ cr 
                    +"%' or NIS like '%"+ cr +"%' or id_buku like '%"+ cr +"%' or tgl_kembali like '%"+ cr +"%' ORDER BY no_kembali DESC" );
             while (rs.next()){
                    Object[] data ={
                    rs.getString("no_kembali"),
                    rs.getString("no_pinjam"),
                    rs.getString("NIS"),
                    rs.getString("id_buku"),
                    rs.getString("tgl_kembali"),
                    rs.getString("denda"),
                    rs.getString("keterangan"),
                    rs.getString("jumlah"),
                    };
                    model.addRow(data);
                    }
              if(tcari.getText().length()<1){
                 tampildata_pengembalian();
             }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton masuk_admin1;
    private javax.swing.JTextField tcari;
    private javax.swing.JTable tkembali;
    // End of variables declaration//GEN-END:variables
}
